### ISSUE TITLE
Erro 500 ao atualizar cliente

### ISSUE THREAD

**Issue by oliveiralex** [guilhermeSobral/dscatalog-bootcamp-devsuperior#1]
Boa tarde Guilherme, tudo bem?

Meu nome é Alexandre e estou corrigindo seu trabalho. Seu trabalho foi aceito, parabéns! Para ficar 100%, peço que você verifique, pois está ocorrendo um erro 500 ao atualizar (PUT) um cliente com id inexistente.",

Abraço e bons estudos

**Comment by guilhermeSobral** [comment]
Boa tarde Alexandre,

Informo que o erro foi corrigido

Att

Em qui., 8 de abr. de 2021 às 12:18, Alexandre ***@***.***>
escreveu:

**Comment by guilhermeSobral** [comment]
Boa tarde Alexandre,

Informo que o erro foi corrigido

Att

**Comment by oliveiralex** [comment]
Beleza Guilherme! 
Vou encerrar a issue!

Abraço
